name: just_do
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_native_splash: ^2.2.19
  rename: ^2.1.1
  hive: ^2.2.3
  hive_generator: ^2.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  path_provider: ^2.0.14
  flutter_svg: ^2.0.4
  dropdown_button2: ^2.0.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  hydrated_bloc: ^9.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf    
        
  
